HIGHER-ORDER-FUNCTION- Higher order function is a functon that receives a function 
                       as an arguments or returns the functon as output,
                         
                         ex. map(), filter(), reduce(), sort() 

   its higher order functon example 
   map(()=>{})
inside map ()=>{} its function arguments 
ex.

let arr=[1,2,3,4,5,6];

const newArray= arr.map((singleArr)=>{return ( singleArr *3 ) })
